version: '3.8'

services:
  app:
    image: wyveo/nginx-php-fpm:php82
    container_name: nginx-php-fpm
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html # Đảm bảo mã nguồn Laravel nằm trong thư mục này
      - ./docker/nginx_log:/var/log/nginx # Thư mục log của Nginx
      - ./docker/php-fpm:/var/log/php-fpm.log # Thư mục log của PHP-FPM
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Cấu hình Nginx
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: